name: Pull Req Workflow

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Clean up node_modules and lock files
        run: |
          rm -rf node_modules pnpm-lock.yaml package-lock.json yarn.lock
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run tests and report issues
        run: pnpm test
      - name: Build project
        run: pnpm run build
